#!/usr/bin/env node

const fs = require('fs');
const path = '../src/assets/model/';
const roundsName = 'rounds.json';
const rounds = JSON.parse(fs.readFileSync(path + roundsName, 'utf8'));
const events = JSON.parse(fs.readFileSync(path + 'events.json', 'utf8'));
const regexp = /[ \-\.\,\(\)]/g;
rounds.forEach(round => {
  const event = events.find(event => event.title === round.event);
  const eventId = round.event.toLowerCase().replace(regexp, '');
  const roundId = round.round.toLowerCase().replace(regexp, '');
  round.eventTitle = round.event;
  round.event = eventId;
  if (event) {
    round.locationTitle = event.location;
  }
  round.id = eventId + '.' + roundId;
});

fs.writeFileSync(roundsName, JSON.stringify(rounds, null, '  '));
