#!/usr/bin/env node

const fs = require('fs');
const list = [
  {
    model: '../src/assets/model/events.json',
    compare: (a, b) => {
      if (a.period.from > b.period.from) {
        return -1;
      }
      if (a.period.from < b.period.from) {
        return 1;
      }
      return 0;
    }
  },
  {
    model: '../src/assets/model/local-events.json',
    compare: (a, b) => {
      if (a.period.from > b.period.from) {
        return -1;
      }
      if (a.period.from < b.period.from) {
        return 1;
      }
      return 0;
    }
  },
  {
    model: '../src/assets/model/rounds.json',
    compare: (a, b) => {
      if (a.date > b.date) {
        return -1;
      }
      if (a.date < b.date) {
        return 1;
      }
      return 0;
    }
  },
];

list.forEach((item, i) => {
  const filepath = __dirname + '/' + item.model;
  const events = JSON.parse(fs.readFileSync(filepath, 'utf8'));
  events.sort(item.compare);
  fs.writeFileSync(filepath, JSON.stringify(events, null, '  '));
  console.log(`#${i+1} ${item.model} done`);
});
