name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Copy environment.prod.ts to environment.ts
        run: cp src/environments/environment.prod.ts src/environments/environment.ts

      - name: Replace Google Maps API Key
        run: sed -i "s|apikey: 'xxxx'|apikey: '${{ secrets.GOOGLE_MAPS_API_KEY }}'|" src/environments/environment.ts
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Grant execute permission to deploy script
        run: chmod +x ./deploy

      - name: Run deploy script
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          ./deploy